/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface OtelLogs {
  Body: Generated<string>;
  LogAttributes: Generated<string>;
  ResourceAttributes: Generated<string>;
  ResourceSchemaUrl: Generated<string>;
  ScopeAttributes: Generated<string>;
  ScopeName: Generated<string>;
  ScopeSchemaUrl: Generated<string>;
  ScopeVersion: Generated<string>;
  ServiceName: Generated<string>;
  SeverityNumber: Generated<number>;
  SeverityText: Generated<string>;
  SpanId: Generated<string>;
  Timestamp: bigint;
  TraceFlags: Generated<number>;
  TraceId: Generated<string>;
}

export interface OtelMetricsExponentialHistogram {
  AggregationTemporality: Generated<string>;
  Attributes: Generated<string>;
  Count: Generated<number>;
  "Exemplars.FilteredAttributes": Generated<string>;
  "Exemplars.SpanId": Generated<string>;
  "Exemplars.TimeUnix": Generated<string>;
  "Exemplars.TraceId": Generated<string>;
  "Exemplars.Value": Generated<string>;
  Max: number | null;
  MetricDescription: Generated<string>;
  MetricName: Generated<string>;
  MetricUnit: Generated<string>;
  Min: number | null;
  NegativeBucketCounts: Generated<string>;
  NegativeOffset: Generated<number>;
  PositiveBucketCounts: Generated<string>;
  PositiveOffset: Generated<number>;
  ResourceAttributes: Generated<string>;
  ResourceSchemaUrl: Generated<string>;
  Scale: Generated<number>;
  ScopeAttributes: Generated<string>;
  ScopeDroppedAttrCount: Generated<number>;
  ScopeName: Generated<string>;
  ScopeSchemaUrl: Generated<string>;
  ScopeVersion: Generated<string>;
  ServiceName: Generated<string>;
  StartTimeUnix: bigint;
  Sum: number | null;
  TimeUnix: bigint;
  ZeroCount: Generated<number>;
  ZeroThreshold: Generated<number>;
}

export interface OtelMetricsGauge {
  Attributes: Generated<string>;
  "Exemplars.FilteredAttributes": Generated<string>;
  "Exemplars.SpanId": Generated<string>;
  "Exemplars.TimeUnix": Generated<string>;
  "Exemplars.TraceId": Generated<string>;
  "Exemplars.Value": Generated<string>;
  Flags: Generated<number>;
  MetricDescription: Generated<string>;
  MetricName: Generated<string>;
  MetricUnit: Generated<string>;
  ResourceAttributes: Generated<string>;
  ResourceSchemaUrl: Generated<string>;
  ScopeAttributes: Generated<string>;
  ScopeDroppedAttrCount: Generated<number>;
  ScopeName: Generated<string>;
  ScopeSchemaUrl: Generated<string>;
  ScopeVersion: Generated<string>;
  ServiceName: Generated<string>;
  StartTimeUnix: bigint;
  TimeUnix: bigint;
  Value: number;
}

export interface OtelMetricsHistogram {
  AggregationTemporality: Generated<string>;
  Attributes: Generated<string>;
  BucketCounts: Generated<string>;
  Count: Generated<number>;
  "Exemplars.FilteredAttributes": Generated<string>;
  "Exemplars.SpanId": Generated<string>;
  "Exemplars.TimeUnix": Generated<string>;
  "Exemplars.TraceId": Generated<string>;
  "Exemplars.Value": Generated<string>;
  ExplicitBounds: Generated<string>;
  Max: number | null;
  MetricDescription: Generated<string>;
  MetricName: Generated<string>;
  MetricUnit: Generated<string>;
  Min: number | null;
  ResourceAttributes: Generated<string>;
  ResourceSchemaUrl: Generated<string>;
  ScopeAttributes: Generated<string>;
  ScopeDroppedAttrCount: Generated<number>;
  ScopeName: Generated<string>;
  ScopeSchemaUrl: Generated<string>;
  ScopeVersion: Generated<string>;
  ServiceName: Generated<string>;
  StartTimeUnix: bigint;
  Sum: number | null;
  TimeUnix: bigint;
}

export interface OtelMetricsSum {
  AggregationTemporality: Generated<string>;
  Attributes: Generated<string>;
  "Exemplars.FilteredAttributes": Generated<string>;
  "Exemplars.SpanId": Generated<string>;
  "Exemplars.TimeUnix": Generated<string>;
  "Exemplars.TraceId": Generated<string>;
  "Exemplars.Value": Generated<string>;
  Flags: Generated<number>;
  IsMonotonic: Generated<number>;
  MetricDescription: Generated<string>;
  MetricName: Generated<string>;
  MetricUnit: Generated<string>;
  ResourceAttributes: Generated<string>;
  ResourceSchemaUrl: Generated<string>;
  ScopeAttributes: Generated<string>;
  ScopeDroppedAttrCount: Generated<number>;
  ScopeName: Generated<string>;
  ScopeSchemaUrl: Generated<string>;
  ScopeVersion: Generated<string>;
  ServiceName: Generated<string>;
  StartTimeUnix: bigint;
  TimeUnix: bigint;
  Value: number;
}

export interface OtelMetricsSummary {
  Attributes: Generated<string>;
  Count: Generated<number>;
  MetricDescription: Generated<string>;
  MetricName: Generated<string>;
  MetricUnit: Generated<string>;
  ResourceAttributes: Generated<string>;
  ResourceSchemaUrl: Generated<string>;
  ScopeAttributes: Generated<string>;
  ScopeDroppedAttrCount: Generated<number>;
  ScopeName: Generated<string>;
  ScopeSchemaUrl: Generated<string>;
  ScopeVersion: Generated<string>;
  ServiceName: Generated<string>;
  StartTimeUnix: bigint;
  Sum: number | null;
  TimeUnix: bigint;
  "ValueAtQuantiles.Quantile": Generated<string>;
  "ValueAtQuantiles.Value": Generated<string>;
}

export interface OtelTraces {
  Duration: Generated<bigint>;
  "Events.Attributes": Generated<string>;
  "Events.Name": Generated<string>;
  "Events.Timestamp": Generated<string>;
  "Links.Attributes": Generated<string>;
  "Links.SpanId": Generated<string>;
  "Links.TraceId": Generated<string>;
  "Links.TraceState": Generated<string>;
  ParentSpanId: Generated<string>;
  ResourceAttributes: Generated<string>;
  ScopeName: Generated<string>;
  ScopeVersion: Generated<string>;
  ServiceName: Generated<string>;
  SpanAttributes: Generated<string>;
  SpanId: string;
  SpanKind: Generated<string>;
  SpanName: Generated<string>;
  StatusCode: Generated<string>;
  StatusMessage: Generated<string>;
  Timestamp: bigint;
  TraceId: string;
  TraceState: Generated<string>;
}

export interface OtelTracesTraceIdTs {
  End: bigint;
  Start: bigint;
  TraceId: string;
}

export interface Dashboards {
  id: string;
  name: string;
  created_at: string;
  metadata: string;
  ui_tree_version: string;
  ui_tree_version_major: number;
  ui_tree: string;
}

export interface DB {
  otel_logs: OtelLogs;
  otel_metrics_exponential_histogram: OtelMetricsExponentialHistogram;
  otel_metrics_gauge: OtelMetricsGauge;
  otel_metrics_histogram: OtelMetricsHistogram;
  otel_metrics_sum: OtelMetricsSum;
  otel_metrics_summary: OtelMetricsSummary;
  otel_traces: OtelTraces;
  otel_traces_trace_id_ts: OtelTracesTraceIdTs;
  dashboards: Dashboards;
}
